### PR TITLE
Add makefile

### PR DESCRIPTION
**Pull request by psteinb**

### CODE REVIEW

**Comment by psteinb** [comment]
I see you reviewed it, but I can still not merge. What does it say for your account?

**Comment by ocaisa** [comment]
I'm not on the list of approving reviewers so that's a blocker

**Comment by psteinb** [comment]
@symulation @razoumov Can you help @ocaisa, please?

**Comment by ChristinaLK** [comment]
Based on @ocaisa's review, I can approve, but we should definitely get him the right permissions to approve himself!

**Pull request merged**
