### PR TITLE
Make all external links/pdfs open in a new tab

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by psteinb** [comment]
I am by no means a javascript expert ... :/

**Comment by psteinb** [comment]
@ocaisa do you have time to resolve the conflicts?

**Comment by tkphd** [comment]
I'm hesitant on the concept here. Middle-clicking, or Ctrl+Click or Shift+Click, is an action every browser supports for opening links in new tabs at the user's discretion. Why is enforcing this for external links necessary or desirable?

Also, the license for the [Jekyll Codex](https://github.com/jhvanderschee/jekyllcodex) is MIT, not "feel free to use." This requires that we include a copyright statement and basic license snippet. The link provided is not sufficient; we would probably have to update our LICENSE.md to explicitly state which part of each file is covered by MIT rather than CC BY.

**Comment by ocaisa** [comment]
The concept here was that it was too easy to move away from the HPC Carpentry page, all of the lessons are external links so clicking on basically anything other than a menu item will immediately take you away from the page (with no link back on the pages you go to). It wouldn't be obvious to the average websurfer that that would be the case, and that they would *need* to use ctrl+click to stay within the page.

I agree with the licence issue though and this particular approach is maybe not the right way to go. Perhaps a better option is to (somehow) use git submodules so that we can build the lessons as part of the main page.

**Comment by ocaisa** [comment]
Closed since #19 got merged

**Pull request closed without merging**
