### PR TITLE
Provide possibility to request a workshop

### PR DESCRIPTION
**Pull request by ocaisa**
(Replaces #42)
Google form for this is at https://forms.gle/hYsoU9p9rvBLuY7X7

### CODE REVIEW

**Comment by ocaisa** [comment]
This PR means we would collect email addresses, so we would need to update our privacy policy accordingly.

**Review by tkphd — COMMENTED** [review]
The form suggests that HPC Carpentry is in a position to provide instructors and helpers. We're pretty accommodating, but I'm not sure we (as a small community) can commit to fulfilling that need.

Perhaps clarity in the drop-down responses would help: from yes-or-no to:

* No, we are all set
* No, but volunteers are welcome to sit in& help
* Yes, and we have asked in the Slack
* Yes, but we have not yet asked

**Comment by ocaisa** [comment]
I've implemented that but perhaps this should wait until tomorrow to discuss a bit further.

**Comment by reid-a** [comment]
I have added an agenda item to the July 15 coordination agenda.

**Review by tkphd — APPROVED** [review]
LGTM. We can address feedback on the specifics of the form separately, getting it linked up on the site is important.

**Pull request merged**
